dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-02/run.sh |
  bash
notifications:
  slack:
    secure: D6Ov9heGPHVv+uVY0yCrxeojX/zs4TJ+96aN8AeDRkNr/3yLANRJZVgQc96VHOtXwPB1ZAr9VTY+QwaCEJtAxalw9iin0qjN5QTY6mmc3/ODOYSYyLoXRcSkNLehpXdnH7Ne7vfmLta8q80kJxtemYydPMoE1agXdevjz7VCq03c/hiYY6U8oz5DnoUUoC1k75AHKaSG7e4sO5xT8m+d8dd1Fp+c81sSST4qvtufV2UMneCG16in967Ce7P/qKO1dQlMQDYfdQCDwe0PO9QsMwoxDebVl6oOpJLvHPl5/VZ80byrTsGvc1g0mW6PwC7mw2obbb7/n/kOXrlaN7PIq3+sfhx7r0q+o8QSjE/q+Y1dFta9Z4aNxb0YH+1QjfFOnFySk0JKqmScrsvW2gs7NRgyLz96Kwl6J2BlGt/7hhI4YjkSv1Q5FWovOZVUNYDfG9fAwb/RGzQPIW5KdyE6UPpSKYbk0s2RvSxH2pxLZVvuKBbLpfMK3fQ2ZlHWM6EvPSPn6rqA0WEVFA8SdnHWae7hxaNiDiyQ4O5b7m+qGfX8jVb5cyGniUZmdfjhK3LBi3x4GSyJXyp4vR0TQ6jMgzR41D31QgfYaM4b3+J0xMBufe1PhajnqbouytWr3TEPC5G1VHRxKJob7ZQCAxzsyEVMGN4W0Mb2iI67NpT3iA4=
